- sendgrid.go
Using current master under go version go1.3.1 linux/amd64, we found that many connections to sendgrid were being orphaned in a `CLOSE_WAIT` state, leading to file descriptors that are never released. We traced the issue to the use of a custom Transport to implement dial timeouts not setting deadlines on other TCP operations (read, write, etc). This PR uses the Client.Timeout field to let the stdlib handle the timing out of connections, while using the DefaultTransport so that other transport defaults are set.
The issue presents itself as thousands of `CLOSE_WAIT` connections to sendgrid when checking `lsof -l`
```
emails TCP ip-10-171-52-54.ec2.internal:39976->184.173.190.226-static.reverse.softlayer.com:https (CLOSE_WAIT)
emails TCP …
```
> Use default transport to close connections, set timeout at client

- README.md
"Examples of common API use cases" link was pointing to sendgrid-java's example use cases.
Submitted my signed CLA so will be waiting on that.
> Update API use cases link to point to sendgrid-go

- sendgrid_test.go
Prism is no longer installed in the users gopath.
Also, if prism is already installed try to update it.
> update prismPath and update prism binary

- helpers/mail/mail_v3.go
Fixes issue [#86](https://github.com/sendgrid/sendgrid-go/issues/86).
I implemented the suggested changes and a little clean up in the SetEnable() functions.
> Simplified code in mail helper

- sendgrid_test.go
@thinkingserious I ran _go test_ (on my windows machine) and it asked me to download prism.exe & place it in _GOPATH/bin_. I did that but it would not work, until I fix the code.
> Fixed code to allow prism.exe to run properly in windows

- helpers/mail/mail_v3.go
- helpers/mail/mail_v3_test.go
- sendgrid.go
- sendgrid_test.go
Fixes #87 
Add new client helper that encapsulates sending an mail
Add a send func for the client that takes an email and triggers the email request
**Sample usage**
``` go
package main
import (
"fmt"
"github.com/sendgrid/sendgrid-go"
"github.com/sendgrid/sendgrid-go/helpers/mail"
"os"
)
func main() {
client := sendgrid.NewSendClient(os.Getenv("SENDGRID_API_KEY"))
from := mail.NewEmail("Example User", "test@example.com")
subject := "Hello World from the SendGrid Go Library"
to := mail.NewEmail("Example User", "test@example.com")
plainTextContent := "some text here"
htmlContent := "<strong>some HTML content</strong>"
email := mail.NewSingleEmail(from, subject, to, plainTextContent, htmlContent)
response, err := client.Send(email)
if err != nil {
log.Println(err)
} else { …
```
> Send a Single Email to a Single Recipient

- helpers/mail/mail_v3.go
As of today the `NewSingleEmail` function doesn't use the right mimetypes which cause mail clients to interprete only the plaintext part of the sent mails. This PR fixes this.
> Fixing mimetypes in the NewSingleEmail function

- USAGE.md
fixes a few grammar errors in [usage.md](https://github.com/sendgrid/sendgrid-go/blob/master/USAGE.md)
> USAGE.MD - Various grammar fixes

- TROUBLESHOOTING.md
The solution for the issue #99 was this warning because the sendgrid.API is a generic function and should not handle this problem.
closes #99
> Added a warning about the error return from sendgrid.API

- examples/accesssettings/accesssettings.go
- examples/alerts/alerts.go
- examples/apikeys/apikeys.go
- examples/asm/asm.go
- examples/browsers/browsers.go
- examples/campaigns/campaigns.go
- examples/categories/categories.go
- examples/clients/clients.go
- examples/contactdb/contactdb.go
- examples/devices/devices.go
- examples/geo/geo.go
- examples/helpers/mail/example.go
- examples/ips/ips.go
- examples/mail/mail.go
- examples/mailboxproviders/mailboxproviders.go
- examples/mailsettings/mailsettings.go
- examples/partnersettings/partnersettings.go
- examples/scopes/scopes.go
- examples/senders/senders.go
- examples/stats/stats.go
- examples/subusers/subusers.go
- examples/suppression/suppression.go
- examples/templates/templates.go
- examples/trackingsettings/trackingsettings.go
- examples/user/user.go
- examples/whitelabel/whitelabel.go
- helpers/mail/mail_v3_test.go
- sendgrid_test.go
- Go fmt fixes
- Fixed Typos
- Go vet fixes
Ref - https://goreportcard.com/report/github.com/sendgrid/sendgrid-go
Ref - Issue #64 
#190
> Go lint fixes

- .gitignore
- helpers/mail/mail_v3_test.go
With this PR, go vet no longer finds any issues in this repository.
Also included a commit to update `.gitignore` to ignore `.swp` file generated by vim.
> Go vet fixes related to #162

- examples/accesssettings/accesssettings.go
- examples/alerts/alerts.go
- examples/apikeys/apikeys.go
- examples/asm/asm.go
- examples/browsers/browsers.go
- examples/campaigns/campaigns.go
- examples/categories/categories.go
- examples/clients/clients.go
- examples/contactdb/contactdb.go
- examples/devices/devices.go
- examples/geo/geo.go
- examples/ips/ips.go
- examples/mail/mail.go
- examples/mailboxproviders/mailboxproviders.go
- examples/mailsettings/mailsettings.go
- examples/partnersettings/partnersettings.go
- examples/scopes/scopes.go
- examples/senders/senders.go
- examples/stats/stats.go
- examples/subusers/subusers.go
- examples/suppression/suppression.go
- examples/templates/templates.go
- examples/trackingsettings/trackingsettings.go
- examples/user/user.go
- examples/whitelabel/whitelabel.go
- helpers/mail/mail_v3.go
- helpers/mail/mail_v3_test.go
- sendgrid.go
This PR will fix golint and gofmt issues with all *.go files.
fixes #64 
`Use: golint and gofmt tool to fix the issue`
> Fixing golint and gofmt errors

- helpers/mail/README.md
The example directory for mail helpers is incorrect in **helpers/mail/README.md**. This fixes that.
It might confuse the user with **examples/mail/mail.go**
> Fix wrong mail helpers example directory in README

- helpers/inbound/inbound.go
Looks more idiomatic and nicer in my opinion
> Initialize map on declaration (round 2)

- sendgrid_test.go
The test case should check the license
date range, if end date is this year.
Fixes #221
> Add test for license date range

- sendgrid_test.go
[honnef.co/go/tools/cmd/megacheck](https://github.com/dominikh/go-tools/tree/master/cmd/megacheck) found 2 small issues:
```
sendgrid_test.go:23:2: var testAPIKey is unused (U1000)
sendgrid_test.go:165:5: should omit comparison to bool constant, can be simplified to !strings.Contains(err.Error(), "Client.Timeout exceeded while awaiting headers") (S1002)
```
This PR removes the unused variable and simplifies the boolean condition.
> Megacheck found 2 small issues

- helpers/mail/mail_v3.go
Fixes #190 
- Fixes spelling issues found by [Go Report Card](https://goreportcard.com/report/github.com/sendgrid/sendgrid-go)
> Fix spelling and formatting of comments in mail_v3.go

- examples/accesssettings/accesssettings.go
- examples/alerts/alerts.go
- examples/apikeys/apikeys.go
- examples/asm/asm.go
- examples/browsers/browsers.go
- examples/campaigns/campaigns.go
- examples/categories/categories.go
- examples/clients/clients.go
- examples/contactdb/contactdb.go
- examples/devices/devices.go
- examples/geo/geo.go
- examples/ips/ips.go
- examples/mail/mail.go
- examples/mailboxproviders/mailboxproviders.go
- examples/mailsettings/mailsettings.go
- examples/partnersettings/partnersettings.go
- examples/scopes/scopes.go
- examples/senders/senders.go
- examples/stats/stats.go
- examples/subusers/subusers.go
- examples/suppression/suppression.go
- examples/templates/templates.go
- examples/trackingsettings/trackingsettings.go
- examples/user/user.go
- examples/whitelabel/whitelabel.go
- helpers/mail/mail_v3.go
- sendgrid.go
> Helping get golint to 100%.

- sendgrid.go
- sendgrid_test.go
This addresses issue https://github.com/sendgrid/sendgrid-go/issues/100.
> Added optional rate limit handling.

- LICENSE.txt
- sendgrid_test.go
Fixes broken license test and repo files test
> fix license and file tests

- .travis.yml
exclude time.Until lint error until we stop supporting Go 1.7 and lower
> exclude time.Until lint error until we stop supporting Go 1.7 and lower

- .gitignore
- USE_CASES.md
- examples/helpers/mail/example.go
- helpers/mail/mail_v3.go
- helpers/mail/mail_v3_test.go
- Add dynamic template support for Go library
- Add helper method for dynamic template data
- Add dynamic template example in examples/helpers/mail/example.go (this had to be done in a separate function because dynamic template data and substitutions may not be used in the same API call
- Add documentation and examples in USE_CASES.md
> Dynamic template support

- helpers/mail/mail_v3_test.go
Related to #266 
- This is a test that provides info about how #266 is getting a strange response,  proving that the problem is not on the client side.
> mail: add test case on empty HTML to NewSingleEmail

- helpers/inbound/inbound_test.go
- helpers/mail/mail_v3_test.go
- sendgrid_test.go
- This starts the change requested in #218 to use assertions instead of standard testing package on test files.
> use testify

- .travis.yml
- go.test.sh
Hello :wave:, 
Thanks sendgrid team for releasing and continually improving this library.
This is a minor fix that excludes code that shouldn't be tested in the examples, vendor, and docker directories.
> Exclude examples from go tests, Travis Job

- USAGE.md
- sendgrid.go
- sendgrid_test.go
- HTTP header "On-Behalf-Of" for API request
- updated tests
- updated docs
> impersonate subuser

- README.md
#326 
Adding details about the sendgrid service plans which is present on the website as Send up to 40,000 emails for 30 days, then send 100 emails/day free forever
Adding details about the sendgrid service plans which is present on the website as Send up to 40,000 emails for 30 days, then send 100 emails/day free forever
>  Modification in Prerequisites

- helpers/mail/mail_v3.go
- helpers/mail/mail_v3_test.go
Fixes #352
- Surrounds names passed to `mail.NewEmail` with double quotes to comply with RFC5322's section on special characters.
> Double quote escape names with special characters

- README.md
This PR fixes a typo that was present in the README. The use cases link wasn't correct.
- Updated usage link in readme
> docs: fix usage link in README

- examples/securewebhook/securewebhook.go
- examples/user/user.go
- helpers/securewebhook/README.md
- helpers/securewebhook/securewebhook.go
- helpers/securewebhook/securewebhook_test.go
Adding support and example for the feature of secure webhook
If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.
> feat: add support and example for secure webhook feature

- .travis.yml
- Dockerfile
Note that the fix only applies to the Docker image which is what's used for executing tests against multiple go versions
> fix: use the last version of testify that works for older go versions

- helpers/mail/mail_v3.go
- helpers/mail/mail_v3_test.go
The backend has been updated to properly handling names with special characters so the original "fix" is no longer needed.
Reverts https://github.com/sendgrid/sendgrid-go/pull/353
Fixes #406
> fix: don't wrap names in double-quotes

- examples/helpers/mail/example.go
- examples/mail/mail.go
- helpers/mail/mail_v3.go
- helpers/mail/mail_v3_test.go
- use-cases/personalization-sending-two-emails-to-two-groups-recipients-from-two-different-from-emails.md
- use-cases/personalization-without-helper-sending-two-emails-to-two-groups-recipients-from-two-different-from-emails.md
- use-cases/personalizations-with-mailer-helper.md
- use-cases/personalizations-without-mailer-helper.md
https://issues.corp.twilio.com/browse/DI-743
>  feat: allow personalization of From name and email for each recipient

- examples/helpers/mail/example.go
- use-cases/attachments-with-mailer-helper.md
- use-cases/attachments-without-mailer-helper.md
This is a minor adjustment to attachment usage with `SetContentID`, hopefully making its use a bit clearer. The "Content-ID" header in a mail message is commonly used to reference the "Content-Disposition: inline;" embedded data within the HTML body. In many implementations the "Content-ID" header is omitted when the disposition is set to "attachment".
https://tools.ietf.org/html/rfc2183
> docs: Update examples using inline attachment with ContentID

- helpers/mail/mail_v3.go
- helpers/mail/mail_v3_test.go
Adds support for the other bypass filters settings as documented here https://sendgrid.com/docs/ui/sending-email/index-suppressions/#bypass-filters-and-v3-mail-send
The code changes just follow the same style as `bypass_list_management` as it's a simple field setting. I updated the tests to show the new fields being set properly. Note: I didn't modify the examples since these 3 new filters are mutually exclusive with `bypass_list_management` so modifying the existing examples will make the request object incorrect.
> feat: Add support for more bypass settings

- helpers/mail/mail_v3.go
- helpers/mail/mail_v3_test.go
Add Email Length validation according to best practices and RFCs
If you have questions, please file a [support ticket](https://support.sendgrid.com), or create a GitHub Issue in this repository.
> feat: add Email Length validation

- base_interface.go
- sendgrid_test.go
Add SendWithContext, MakeRequestWithContext, MakeRequestRetryWithContext and MakeRequestAsyncWithContext.
closes #403 
If you have questions, please file a [support ticket](https://support.sendgrid.com), or create a GitHub Issue in this repository.
> feat: support context.Context

- .travis.yml
- Dockerfile
- README.md
Add travis tests against v1.16 (without supporting go modules)
> chore: add support for 1.16

- .gitignore
- USAGE.md
- sendgrid.go
- sendgrid_test.go
The sendgrid documentation (and my own findings) say that the mail.send endpoint
does not support using the `on-behalf-of` header.
[Documentation](
https://docs.sendgrid.com/api-reference/how-to-use-the-sendgrid-v3-api/on-behalf-of-subuser
)
Providing the `NewSendClientSubuser` in this SDK causes wasted time because it
sets the expectation that this is possible when it is not.
I also added guards to the `GetRequestSubuser` function to prevent people from
using it with the mail.send endpoint.
A short description of what this PR does.
> chore: Remove mail.send helpers with on-behalf-of header

- .github/workflows/test-and-deploy.yml
- README.md
- sendgrid_test.go
Does a gh release on tagged commits
> chore: merge test and gh release workflows

- .github/workflows/test-and-deploy.yml
- README.md
- helpers/inbound/inbound.go
- helpers/inbound/inbound_test.go
- sendgrid_test.go
- use-cases/attachments-with-mailer-helper.md
This PR updates the application to be compatible with go 1.19
If you have questions, please file a [support ticket](https://support.sendgrid.com).
> feat: go 1.19 compatibility

- base_interface.go
- sendgrid_test.go
[Mail body compression](https://docs.sendgrid.com/api-reference/mail-send/mail-send#mail-body-compression) is supported on V3 api. This patch added the support that when a client sets the content-encoding header to gzip, send compresses the mail body with gzip.
> feat: gzip mail body when content-encoding is set to gzip

- base_interface.go
- examples/dataresidency/setRegion.go
- sendgrid.go
- sendgrid_test.go
Added region field in sendgrid options. The default region is "global" and the default host is "api.sendgrid.com". When the region is set to "eu", the host should change to "api.eu.sendgrid.com".
If you have questions, please file a [support ticket](https://support.sendgrid.com).
> feat: added data residency for eu and global regions

- base_interface.go
- sendgrid.go
- sendgrid_test.go
1. Removed public SetHost() as it is not required for Go [SetDataResidency does exactly the same thing]
2. Shifted SetDataResidency() to sendgrid.go since it is specific to that only. Earlier it was in base_interface.go which means if someone creates a twilio_email request, then also they would be able to access SetDataResidency() and overrides host. But that doesn't make sense since it is specific to sendgrid only.
If you have questions, please file a [support ticket](https://support.sendgrid.com).
> chore: removed SetHost and shifted SetDataResidency to sendgrid.go

- helpers/mail/mail_v3.go
- helpers/mail/mail_v3_test.go
Add reply_to_list functionality. It just implements a feature that is available on api but not yet on the SDK (and should).
> feat: add mail_v3 functionality for reply_to_list

- .github/workflows/test-and-deploy.yml
- Dockerfile
- LICENSE
1. As of [Go 1.22](https://go.dev/doc/go1.22#go-command), “go get is no longer supported outside of a module”, Thus it was failing go get command.
**Failure:** 
```
0.256 go get -t -v ./...
0.258 go: modules disabled by GO111MODULE=off; see 'go help modules'
```
**Link**: https://github.com/sendgrid/sendgrid-go/actions/runs/9859530453/job/27223508248#step:6:231
**Issue**: https://github.com/golang/go/issues/66080
If you have questions, please file a [support ticket](https://support.sendgrid.com).
> chore: fixed failed test cases due to go upgrade
