README.md
Small change to add the GoDoc badge.
AND, awesome, awesome job getting our client libs to support API keys!
=> Adding reference to GoDoc badge.

README.md
Hi @eddiezane,
Here is a pr example of how easy it is to use gopkg.in for nicer versioning.  Since this repo is already tagged...gopkg.in is able to recognize it automatically.  :)  Good work!
-R
=> Update to use gopkg.in going forward for nicer versioning.

README.md
Fixed sample code of AddAttachmentFromStream().
Sample code is different from implemented code.
https://github.com/sendgrid/sendgrid-go/blob/master/mail.go#L221
=> Fixed Sample Code in README.md

README.md, sendgrid.env.template
Still have some concerns re: using env vars on multi-tenant systems but this is far better than people writing their creds out in code and checking them into public repos.
=> Update example to use API key as environment variable

CONTRIBUTING.md, helpers/mail/mail_v3.go, helpers/mail/mail_v3_test.go
https://github.com/sendgrid/sendgrid-go/issues/68
=> 68 disable subscription tracking

helpers/mail/mail_v3.go
Hello there !
It was simple enough and did not break anything :)
=> make contents var args in NewV3MailInit

README.md, TROUBLESHOOTING.md, USAGE.md, USE_CASES.md, examples/accesssettings/accesssettings.go, examples/alerts/alerts.go, examples/apikeys/apikeys.go, examples/asm/asm.go, examples/browsers/browsers.go, examples/campaigns/campaigns.go, examples/categories/categories.go, examples/clients/clients.go, examples/contactdb/contactdb.go, examples/devices/devices.go, examples/geo/geo.go, examples/ips/ips.go, examples/mail/mail.go, examples/mailboxproviders/mailboxproviders.go, examples/mailsettings/mailsettings.go, examples/partnersettings/partnersettings.go, examples/scopes/scopes.go, examples/senders/senders.go, examples/stats/stats.go, examples/subusers/subusers.go, examples/suppression/suppression.go, examples/templates/templates.go, examples/trackingsettings/trackingsettings.go, examples/user/user.go, examples/whitelabel/whitelabel.go, helpers/mail/mail_v3.go
https://github.com/sendgrid/sendgrid-go/issues/86
=> Use log instead of fmt for printing errors

USE_CASES.md
Added examples for attachments with and without mail helper functions. Attachments added include .txt, .jpg and .pdf.
=> Go attachments

README.md
=> Moved logo to top and added more badges

CONTRIBUTING.md, README.md, USAGE.md, USE_CASES.md
#184 
@mbernier edit:
closes #184
=> Making README/Doc sections more SEO friendly

TROUBLESHOOTING.md
#178 
@mbernier edit: closes #178
=> Add review request body section to TROUBLESHOOTING.md

sendgrid.go
More idiomatic perhaps, but looks nicer in my opinion
=> Initialize map on declaration

helpers/inbound/inbound.go, helpers/mail/mail_v3_test.go
`gocyclo` fix for issue - #190 
-  `inbound.go` - created helper methods to abstract the logic
- `mail_v3_test.go` - created helper method for field validation `validateEmailField`
Report card - https://goreportcard.com/report/github.com/srini156/sendgrid-go
=> Fix for gocyclo - reducing cyclomatic complexity

LICENSE.txt
=> update LICENSE - set correct year

.gitignore, README.md
=> Add a .env_sample file, update gitignore, update README.md

.travis.yml, helpers/inbound/inbound.go
- Added the [gometalinter](https://github.com/alecthomas/gometalinter) to the TravisCI build
- Enabled the following linters `errcheck,vet,vetshadow,megacheck` for starters.
- Invoked [gometalinter](https://github.com/alecthomas/gometalinter) twice in the following paths: `.` and `helpers/...` to avoid numerous warnings in the `examples` folder.
- Fixed a few small issues found by the enabled linters.
```
gometalinter --disable-all --enable=errcheck --enable=vet --enable=vetshadow --enable=megacheck helpers/...
helpers/inbound/inbound.go:70::warning: declaration of "err" shadows declaration at helpers/inbound/inbound.go:67 (vetshadow)
helpers/inbound/inbound.go:165::warning: declaration of "value" shadows declaration at helpers/inbound/inbound.go:149 (vetshadow) …
```
=> Include Gometalinter in Travis CI build

sendgrid_test.go
To check if some specific files exist
in the repository.
Fixes #222
=> Add test for checking specific repo files

.gitignore
- add coverage.txt to .gitignore
=> add coverage.txt to .gitignore

README.md, helpers/inbound/inbound.go
- Update Readme tags
- Fix a minor linter error
=> readme tag update and linter error fix

helpers/mail/mail_v3_test.go
- This PR finishes adding testify to the tests
=> helpers/mail: add testify to new test

TROUBLESHOOTING.md
Fixes #291 
- Fix broken link.
=> fix broken link

helpers/inbound/README.md
Fixes broken links in readme to github file 
- [-] I have added tests that prove my fix is effective or that my feature works
=> inbound: fix readme links

docker/Dockerfile
Hello,
Most commands can work with absolute paths and it in most cases not necessary to change directories.
So, Removed unnecessary code to improve readability.
What do you think of it?
Thanks
test log:
```
root@ubuntu:~/sendgrid-go/docker# docker build -t app .
Sending build context to Docker daemon  16.9 kB
Step 1/10 : FROM golang:1.9.1
1.9.1: Pulling from library/golang
3e17c6eae66c: Pull complete 
74d44b20f851: Pull complete 
a156217f3fa4: Pull complete 
4a1ed13b6faa: Pull complete 
dc8a629d8a36: Pull complete 
431925b1aca5: Pull complete 
2ac2306b8d4c: Pull complete 
84664a55d30a: Pull complete 
Digest: sha256:e2be086d86eeb789460bcb48bc26e95c5b04a61fe8cf720ae1b2195d6f40edc4
Status: Downloaded newer image for golang:1.9.1
---> 99e596fc807e
Step 2/10 : ENV OAI_SPEC_URL …
```
=> clean up dockerfile

CONTRIBUTING.md, TROUBLESHOOTING.md, USAGE.md, helpers/inbound/README.md
=> docs: Correct *.md files using Grammarly

USAGE.md, examples/emailactivity/emailactivity.go, use-cases/email-activity.md
- Add examples for Email Activity API
- Add use case for Email Activity API
- Add usage for Email Activity API
=> docs: Email activity API Documentation

helpers/mail/mail_v3.go, helpers/mail/mail_v3_test.go
=> fix: typo in method name

CHANGELOG.md, base_interface.go
Updated version and changelog for manual release
=> chore: updates for manual release
